language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_3f94d4717d53_key -iv $encrypted_3f94d4717d53_iv
  -in ./tests/.clasprc.json.enc -out .clasprc.json -d || true
install: yarn
chache:
  cache: yarn
  directories: node_modules
before_script:
- yarn run clasp login --creds .clasprc.json || true
script:
- yarn run clasp push
- yarn run clasp deploy -i "${GAS_DEPKOYMENT_ID}"
branches:
  only:
  - master
env:
  global:
  - secure: im5/W6toyGTY+RvKw1cXkJ57h9FalTKJM8uZd5+Fhpr43U0cO3wLQCUlXAhS1cxrgA25F41pBw0xxRdiMu3OG7K1kFZvsequKzDzs9YGqjh6pNCStqQeBstlC/5x5Nl+CGSiZKjexcvZzrA/Rf/AOjpKPrMgEWqVRj5ma9d/e8QbaMxlPvPuZz0GgfGlXyM2liyDSnzFVOXFBby5AjfxZZJw0/eiT6sQuIXq4CyktAYE0tdomFt/mjMEjsvSkrH+GSTWGMNL3tlkQCnxN6Rb52ICunAITMS+l3Mw7WppJt+HH89MwbXb8H15a1V5AepzHa+eOca8nQowbGPl8vzgcBtkuPAvSqjXcqqlTRjIfI5N2ubOClc8xQb/PVLKoHE6x6sNvUavbMrpfpJnb3KmRbCy8m2J7PKEVs5aXrcAUE18COCbncw7jaFlhZ9wqe6oKWv73/QbREXRBPtD16dJ8G8KxFn8H8DUlj1sDg608aY6B8+VpZWiElGDj0ZiT/hADFtwQasHJfhW9KoobkFbgCGcpcWsmLP0Qju0uqcPzhxWSL5vl4M5UOXbgFirM+1L15ID6ZV1sbMxhKxPr25VN+n+4NptkPxoJxcXE3w+0mTJw2CGQv/lrT9LZ1+9G1IsV6e1jpFq0jQ2b0hMDKsI7eqUOUDeS5iPs8ECnpWPkSw=
  - secure: BobAC5wxxNL762/JXzWBlmnUFQZPm6gnd8T2JqJ3B3XV5kxeulQstkbb1MfEIzPcDNtgf8EYcRhKCA3w6AY4jl3GGcWIH3wt5cAb0BgDrn0MSpMpnTVMKOytsviM1PdzzcrIbcoULljJEr5dCB8saoeznIXlnnIS62zlDET8IwQmuAP5/yhxoBI/8ovOinhZdpbCV0eW7FoRC/JFqeojj7XZ1eCaCUwj1FAi4SL0C4b2sMjijtekirSb8cCCjmEse0UQxec8k+HCGp4CPZftkFmAuzz87sWmhSzuuYVbP8cozgmIrC3m4yoqMhwbC2NgXy9maku8aFsnv5lrVOajoeQtF1j9pM+HNRceOCmDp+JuBJ0eDg2iEhzoJjSIhytRKJeeke6548LmBvJ3+KLQ6sqzkzPXGcB61yE6dm93O9PXZFyyn5mYOdF94BpYjs0bLIO0Ug9UdbIRhI/N+wnMj77Dv8Lsmf6W7aEWEgVlSjd3qPrRNeDOlzbgPZPFwuc2k8Q33hdBD/foXh/C6InzCnC7Q5l3g/vgFZ4vV/tfykdTjUroDk1KhQPXqsQ+oL3Z6QsNYSbhR55Tg/vB+IRiYIaVw4aN5Y3NJ2ElDarUzixrAf7M/55Ust+BTuq6OkINyLM2Ny2gKdEx6KD/gUsqzl+qpSHPQiLcvRslPC+THKw=
